// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrix_mul_Loop_VITIS_LOOP_38_1_proc_Pipeline_init_c (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        local_C_address0,
        local_C_ce0,
        local_C_we0,
        local_C_d0,
        local_C_1_address0,
        local_C_1_ce0,
        local_C_1_we0,
        local_C_1_d0,
        local_C_2_address0,
        local_C_2_ce0,
        local_C_2_we0,
        local_C_2_d0,
        local_C_3_address0,
        local_C_3_ce0,
        local_C_3_we0,
        local_C_3_d0,
        local_C_4_address0,
        local_C_4_ce0,
        local_C_4_we0,
        local_C_4_d0,
        local_C_5_address0,
        local_C_5_ce0,
        local_C_5_we0,
        local_C_5_d0,
        local_C_6_address0,
        local_C_6_ce0,
        local_C_6_we0,
        local_C_6_d0,
        local_C_7_address0,
        local_C_7_ce0,
        local_C_7_we0,
        local_C_7_d0,
        local_C_8_address0,
        local_C_8_ce0,
        local_C_8_we0,
        local_C_8_d0,
        local_C_9_address0,
        local_C_9_ce0,
        local_C_9_we0,
        local_C_9_d0,
        local_C_10_address0,
        local_C_10_ce0,
        local_C_10_we0,
        local_C_10_d0,
        local_C_11_address0,
        local_C_11_ce0,
        local_C_11_we0,
        local_C_11_d0,
        local_C_12_address0,
        local_C_12_ce0,
        local_C_12_we0,
        local_C_12_d0,
        local_C_13_address0,
        local_C_13_ce0,
        local_C_13_we0,
        local_C_13_d0,
        local_C_14_address0,
        local_C_14_ce0,
        local_C_14_we0,
        local_C_14_d0,
        local_C_15_address0,
        local_C_15_ce0,
        local_C_15_we0,
        local_C_15_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] local_C_address0;
output   local_C_ce0;
output   local_C_we0;
output  [31:0] local_C_d0;
output  [3:0] local_C_1_address0;
output   local_C_1_ce0;
output   local_C_1_we0;
output  [31:0] local_C_1_d0;
output  [3:0] local_C_2_address0;
output   local_C_2_ce0;
output   local_C_2_we0;
output  [31:0] local_C_2_d0;
output  [3:0] local_C_3_address0;
output   local_C_3_ce0;
output   local_C_3_we0;
output  [31:0] local_C_3_d0;
output  [3:0] local_C_4_address0;
output   local_C_4_ce0;
output   local_C_4_we0;
output  [31:0] local_C_4_d0;
output  [3:0] local_C_5_address0;
output   local_C_5_ce0;
output   local_C_5_we0;
output  [31:0] local_C_5_d0;
output  [3:0] local_C_6_address0;
output   local_C_6_ce0;
output   local_C_6_we0;
output  [31:0] local_C_6_d0;
output  [3:0] local_C_7_address0;
output   local_C_7_ce0;
output   local_C_7_we0;
output  [31:0] local_C_7_d0;
output  [3:0] local_C_8_address0;
output   local_C_8_ce0;
output   local_C_8_we0;
output  [31:0] local_C_8_d0;
output  [3:0] local_C_9_address0;
output   local_C_9_ce0;
output   local_C_9_we0;
output  [31:0] local_C_9_d0;
output  [3:0] local_C_10_address0;
output   local_C_10_ce0;
output   local_C_10_we0;
output  [31:0] local_C_10_d0;
output  [3:0] local_C_11_address0;
output   local_C_11_ce0;
output   local_C_11_we0;
output  [31:0] local_C_11_d0;
output  [3:0] local_C_12_address0;
output   local_C_12_ce0;
output   local_C_12_we0;
output  [31:0] local_C_12_d0;
output  [3:0] local_C_13_address0;
output   local_C_13_ce0;
output   local_C_13_we0;
output  [31:0] local_C_13_d0;
output  [3:0] local_C_14_address0;
output   local_C_14_ce0;
output   local_C_14_we0;
output  [31:0] local_C_14_d0;
output  [3:0] local_C_15_address0;
output   local_C_15_ce0;
output   local_C_15_we0;
output  [31:0] local_C_15_d0;

reg ap_idle;
reg local_C_ce0;
reg local_C_we0;
reg local_C_1_ce0;
reg local_C_1_we0;
reg local_C_2_ce0;
reg local_C_2_we0;
reg local_C_3_ce0;
reg local_C_3_we0;
reg local_C_4_ce0;
reg local_C_4_we0;
reg local_C_5_ce0;
reg local_C_5_we0;
reg local_C_6_ce0;
reg local_C_6_we0;
reg local_C_7_ce0;
reg local_C_7_we0;
reg local_C_8_ce0;
reg local_C_8_we0;
reg local_C_9_ce0;
reg local_C_9_we0;
reg local_C_10_ce0;
reg local_C_10_we0;
reg local_C_11_ce0;
reg local_C_11_we0;
reg local_C_12_ce0;
reg local_C_12_we0;
reg local_C_13_ce0;
reg local_C_13_we0;
reg local_C_14_ce0;
reg local_C_14_we0;
reg local_C_15_ce0;
reg local_C_15_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln43_fu_294_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln43_fu_306_p1;
reg   [4:0] ii_fu_58;
wire   [4:0] add_ln43_fu_300_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_ii_2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

matrix_mul_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln43_fu_294_p2 == 1'd0)) begin
            ii_fu_58 <= add_ln43_fu_300_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ii_fu_58 <= 5'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ii_2 = 5'd0;
    end else begin
        ap_sig_allocacmp_ii_2 = ii_fu_58;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_10_ce0 = 1'b1;
    end else begin
        local_C_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_10_we0 = 1'b1;
    end else begin
        local_C_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_11_ce0 = 1'b1;
    end else begin
        local_C_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_11_we0 = 1'b1;
    end else begin
        local_C_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_12_ce0 = 1'b1;
    end else begin
        local_C_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_12_we0 = 1'b1;
    end else begin
        local_C_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_13_ce0 = 1'b1;
    end else begin
        local_C_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_13_we0 = 1'b1;
    end else begin
        local_C_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_14_ce0 = 1'b1;
    end else begin
        local_C_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_14_we0 = 1'b1;
    end else begin
        local_C_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_15_ce0 = 1'b1;
    end else begin
        local_C_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_15_we0 = 1'b1;
    end else begin
        local_C_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_1_ce0 = 1'b1;
    end else begin
        local_C_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_1_we0 = 1'b1;
    end else begin
        local_C_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_2_ce0 = 1'b1;
    end else begin
        local_C_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_2_we0 = 1'b1;
    end else begin
        local_C_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_3_ce0 = 1'b1;
    end else begin
        local_C_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_3_we0 = 1'b1;
    end else begin
        local_C_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_4_ce0 = 1'b1;
    end else begin
        local_C_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_4_we0 = 1'b1;
    end else begin
        local_C_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_5_ce0 = 1'b1;
    end else begin
        local_C_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_5_we0 = 1'b1;
    end else begin
        local_C_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_6_ce0 = 1'b1;
    end else begin
        local_C_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_6_we0 = 1'b1;
    end else begin
        local_C_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_7_ce0 = 1'b1;
    end else begin
        local_C_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_7_we0 = 1'b1;
    end else begin
        local_C_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_8_ce0 = 1'b1;
    end else begin
        local_C_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_8_we0 = 1'b1;
    end else begin
        local_C_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_9_ce0 = 1'b1;
    end else begin
        local_C_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_9_we0 = 1'b1;
    end else begin
        local_C_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_ce0 = 1'b1;
    end else begin
        local_C_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln43_fu_294_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        local_C_we0 = 1'b1;
    end else begin
        local_C_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln43_fu_300_p2 = (ap_sig_allocacmp_ii_2 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln43_fu_294_p2 = ((ap_sig_allocacmp_ii_2 == 5'd16) ? 1'b1 : 1'b0);

assign local_C_10_address0 = zext_ln43_fu_306_p1;

assign local_C_10_d0 = 32'd0;

assign local_C_11_address0 = zext_ln43_fu_306_p1;

assign local_C_11_d0 = 32'd0;

assign local_C_12_address0 = zext_ln43_fu_306_p1;

assign local_C_12_d0 = 32'd0;

assign local_C_13_address0 = zext_ln43_fu_306_p1;

assign local_C_13_d0 = 32'd0;

assign local_C_14_address0 = zext_ln43_fu_306_p1;

assign local_C_14_d0 = 32'd0;

assign local_C_15_address0 = zext_ln43_fu_306_p1;

assign local_C_15_d0 = 32'd0;

assign local_C_1_address0 = zext_ln43_fu_306_p1;

assign local_C_1_d0 = 32'd0;

assign local_C_2_address0 = zext_ln43_fu_306_p1;

assign local_C_2_d0 = 32'd0;

assign local_C_3_address0 = zext_ln43_fu_306_p1;

assign local_C_3_d0 = 32'd0;

assign local_C_4_address0 = zext_ln43_fu_306_p1;

assign local_C_4_d0 = 32'd0;

assign local_C_5_address0 = zext_ln43_fu_306_p1;

assign local_C_5_d0 = 32'd0;

assign local_C_6_address0 = zext_ln43_fu_306_p1;

assign local_C_6_d0 = 32'd0;

assign local_C_7_address0 = zext_ln43_fu_306_p1;

assign local_C_7_d0 = 32'd0;

assign local_C_8_address0 = zext_ln43_fu_306_p1;

assign local_C_8_d0 = 32'd0;

assign local_C_9_address0 = zext_ln43_fu_306_p1;

assign local_C_9_d0 = 32'd0;

assign local_C_address0 = zext_ln43_fu_306_p1;

assign local_C_d0 = 32'd0;

assign zext_ln43_fu_306_p1 = ap_sig_allocacmp_ii_2;

endmodule //matrix_mul_Loop_VITIS_LOOP_38_1_proc_Pipeline_init_c
