// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrix_mul_matrix_mul_Pipeline_VITIS_LOOP_54_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        local_B_address0,
        local_B_ce0,
        local_B_we0,
        local_B_d0,
        local_B_1_address0,
        local_B_1_ce0,
        local_B_1_we0,
        local_B_1_d0,
        local_B_2_address0,
        local_B_2_ce0,
        local_B_2_we0,
        local_B_2_d0,
        local_B_3_address0,
        local_B_3_ce0,
        local_B_3_we0,
        local_B_3_d0,
        local_B_4_address0,
        local_B_4_ce0,
        local_B_4_we0,
        local_B_4_d0,
        local_B_5_address0,
        local_B_5_ce0,
        local_B_5_we0,
        local_B_5_d0,
        local_B_6_address0,
        local_B_6_ce0,
        local_B_6_we0,
        local_B_6_d0,
        local_B_7_address0,
        local_B_7_ce0,
        local_B_7_we0,
        local_B_7_d0,
        local_B_8_address0,
        local_B_8_ce0,
        local_B_8_we0,
        local_B_8_d0,
        local_B_9_address0,
        local_B_9_ce0,
        local_B_9_we0,
        local_B_9_d0,
        local_B_10_address0,
        local_B_10_ce0,
        local_B_10_we0,
        local_B_10_d0,
        local_B_11_address0,
        local_B_11_ce0,
        local_B_11_we0,
        local_B_11_d0,
        local_B_12_address0,
        local_B_12_ce0,
        local_B_12_we0,
        local_B_12_d0,
        local_B_13_address0,
        local_B_13_ce0,
        local_B_13_we0,
        local_B_13_d0,
        local_B_14_address0,
        local_B_14_ce0,
        local_B_14_we0,
        local_B_14_d0,
        local_B_15_address0,
        local_B_15_ce0,
        local_B_15_we0,
        local_B_15_d0,
        local_B_16_address0,
        local_B_16_ce0,
        local_B_16_we0,
        local_B_16_d0,
        local_B_17_address0,
        local_B_17_ce0,
        local_B_17_we0,
        local_B_17_d0,
        local_B_18_address0,
        local_B_18_ce0,
        local_B_18_we0,
        local_B_18_d0,
        local_B_19_address0,
        local_B_19_ce0,
        local_B_19_we0,
        local_B_19_d0,
        local_B_20_address0,
        local_B_20_ce0,
        local_B_20_we0,
        local_B_20_d0,
        local_B_21_address0,
        local_B_21_ce0,
        local_B_21_we0,
        local_B_21_d0,
        local_B_22_address0,
        local_B_22_ce0,
        local_B_22_we0,
        local_B_22_d0,
        local_B_23_address0,
        local_B_23_ce0,
        local_B_23_we0,
        local_B_23_d0,
        local_B_24_address0,
        local_B_24_ce0,
        local_B_24_we0,
        local_B_24_d0,
        local_B_25_address0,
        local_B_25_ce0,
        local_B_25_we0,
        local_B_25_d0,
        local_B_26_address0,
        local_B_26_ce0,
        local_B_26_we0,
        local_B_26_d0,
        local_B_27_address0,
        local_B_27_ce0,
        local_B_27_we0,
        local_B_27_d0,
        local_B_28_address0,
        local_B_28_ce0,
        local_B_28_we0,
        local_B_28_d0,
        local_B_29_address0,
        local_B_29_ce0,
        local_B_29_we0,
        local_B_29_d0,
        local_B_30_address0,
        local_B_30_ce0,
        local_B_30_we0,
        local_B_30_d0,
        local_B_31_address0,
        local_B_31_ce0,
        local_B_31_we0,
        local_B_31_d0,
        local_B_32_address0,
        local_B_32_ce0,
        local_B_32_we0,
        local_B_32_d0,
        local_B_33_address0,
        local_B_33_ce0,
        local_B_33_we0,
        local_B_33_d0,
        local_B_34_address0,
        local_B_34_ce0,
        local_B_34_we0,
        local_B_34_d0,
        local_B_35_address0,
        local_B_35_ce0,
        local_B_35_we0,
        local_B_35_d0,
        local_B_36_address0,
        local_B_36_ce0,
        local_B_36_we0,
        local_B_36_d0,
        local_B_37_address0,
        local_B_37_ce0,
        local_B_37_we0,
        local_B_37_d0,
        local_B_38_address0,
        local_B_38_ce0,
        local_B_38_we0,
        local_B_38_d0,
        local_B_39_address0,
        local_B_39_ce0,
        local_B_39_we0,
        local_B_39_d0,
        local_B_40_address0,
        local_B_40_ce0,
        local_B_40_we0,
        local_B_40_d0,
        local_B_41_address0,
        local_B_41_ce0,
        local_B_41_we0,
        local_B_41_d0,
        local_B_42_address0,
        local_B_42_ce0,
        local_B_42_we0,
        local_B_42_d0,
        local_B_43_address0,
        local_B_43_ce0,
        local_B_43_we0,
        local_B_43_d0,
        local_B_44_address0,
        local_B_44_ce0,
        local_B_44_we0,
        local_B_44_d0,
        local_B_45_address0,
        local_B_45_ce0,
        local_B_45_we0,
        local_B_45_d0,
        local_B_46_address0,
        local_B_46_ce0,
        local_B_46_we0,
        local_B_46_d0,
        local_B_47_address0,
        local_B_47_ce0,
        local_B_47_we0,
        local_B_47_d0,
        local_B_48_address0,
        local_B_48_ce0,
        local_B_48_we0,
        local_B_48_d0,
        local_B_49_address0,
        local_B_49_ce0,
        local_B_49_we0,
        local_B_49_d0,
        local_B_50_address0,
        local_B_50_ce0,
        local_B_50_we0,
        local_B_50_d0,
        local_B_51_address0,
        local_B_51_ce0,
        local_B_51_we0,
        local_B_51_d0,
        local_B_52_address0,
        local_B_52_ce0,
        local_B_52_we0,
        local_B_52_d0,
        local_B_53_address0,
        local_B_53_ce0,
        local_B_53_we0,
        local_B_53_d0,
        local_B_54_address0,
        local_B_54_ce0,
        local_B_54_we0,
        local_B_54_d0,
        local_B_55_address0,
        local_B_55_ce0,
        local_B_55_we0,
        local_B_55_d0,
        local_B_56_address0,
        local_B_56_ce0,
        local_B_56_we0,
        local_B_56_d0,
        local_B_57_address0,
        local_B_57_ce0,
        local_B_57_we0,
        local_B_57_d0,
        local_B_58_address0,
        local_B_58_ce0,
        local_B_58_we0,
        local_B_58_d0,
        local_B_59_address0,
        local_B_59_ce0,
        local_B_59_we0,
        local_B_59_d0,
        local_B_60_address0,
        local_B_60_ce0,
        local_B_60_we0,
        local_B_60_d0,
        local_B_61_address0,
        local_B_61_ce0,
        local_B_61_we0,
        local_B_61_d0,
        local_B_62_address0,
        local_B_62_ce0,
        local_B_62_we0,
        local_B_62_d0,
        local_B_63_address0,
        local_B_63_ce0,
        local_B_63_we0,
        local_B_63_d0,
        zext_ln34_1,
        trunc_ln35_1,
        shl_ln,
        B,
        grp_fu_5051_p_din0,
        grp_fu_5051_p_din1,
        grp_fu_5051_p_dout0,
        grp_fu_5051_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [31:0] m_axi_gmem1_WDATA;
output  [3:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [31:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
output  [5:0] local_B_address0;
output   local_B_ce0;
output   local_B_we0;
output  [31:0] local_B_d0;
output  [5:0] local_B_1_address0;
output   local_B_1_ce0;
output   local_B_1_we0;
output  [31:0] local_B_1_d0;
output  [5:0] local_B_2_address0;
output   local_B_2_ce0;
output   local_B_2_we0;
output  [31:0] local_B_2_d0;
output  [5:0] local_B_3_address0;
output   local_B_3_ce0;
output   local_B_3_we0;
output  [31:0] local_B_3_d0;
output  [5:0] local_B_4_address0;
output   local_B_4_ce0;
output   local_B_4_we0;
output  [31:0] local_B_4_d0;
output  [5:0] local_B_5_address0;
output   local_B_5_ce0;
output   local_B_5_we0;
output  [31:0] local_B_5_d0;
output  [5:0] local_B_6_address0;
output   local_B_6_ce0;
output   local_B_6_we0;
output  [31:0] local_B_6_d0;
output  [5:0] local_B_7_address0;
output   local_B_7_ce0;
output   local_B_7_we0;
output  [31:0] local_B_7_d0;
output  [5:0] local_B_8_address0;
output   local_B_8_ce0;
output   local_B_8_we0;
output  [31:0] local_B_8_d0;
output  [5:0] local_B_9_address0;
output   local_B_9_ce0;
output   local_B_9_we0;
output  [31:0] local_B_9_d0;
output  [5:0] local_B_10_address0;
output   local_B_10_ce0;
output   local_B_10_we0;
output  [31:0] local_B_10_d0;
output  [5:0] local_B_11_address0;
output   local_B_11_ce0;
output   local_B_11_we0;
output  [31:0] local_B_11_d0;
output  [5:0] local_B_12_address0;
output   local_B_12_ce0;
output   local_B_12_we0;
output  [31:0] local_B_12_d0;
output  [5:0] local_B_13_address0;
output   local_B_13_ce0;
output   local_B_13_we0;
output  [31:0] local_B_13_d0;
output  [5:0] local_B_14_address0;
output   local_B_14_ce0;
output   local_B_14_we0;
output  [31:0] local_B_14_d0;
output  [5:0] local_B_15_address0;
output   local_B_15_ce0;
output   local_B_15_we0;
output  [31:0] local_B_15_d0;
output  [5:0] local_B_16_address0;
output   local_B_16_ce0;
output   local_B_16_we0;
output  [31:0] local_B_16_d0;
output  [5:0] local_B_17_address0;
output   local_B_17_ce0;
output   local_B_17_we0;
output  [31:0] local_B_17_d0;
output  [5:0] local_B_18_address0;
output   local_B_18_ce0;
output   local_B_18_we0;
output  [31:0] local_B_18_d0;
output  [5:0] local_B_19_address0;
output   local_B_19_ce0;
output   local_B_19_we0;
output  [31:0] local_B_19_d0;
output  [5:0] local_B_20_address0;
output   local_B_20_ce0;
output   local_B_20_we0;
output  [31:0] local_B_20_d0;
output  [5:0] local_B_21_address0;
output   local_B_21_ce0;
output   local_B_21_we0;
output  [31:0] local_B_21_d0;
output  [5:0] local_B_22_address0;
output   local_B_22_ce0;
output   local_B_22_we0;
output  [31:0] local_B_22_d0;
output  [5:0] local_B_23_address0;
output   local_B_23_ce0;
output   local_B_23_we0;
output  [31:0] local_B_23_d0;
output  [5:0] local_B_24_address0;
output   local_B_24_ce0;
output   local_B_24_we0;
output  [31:0] local_B_24_d0;
output  [5:0] local_B_25_address0;
output   local_B_25_ce0;
output   local_B_25_we0;
output  [31:0] local_B_25_d0;
output  [5:0] local_B_26_address0;
output   local_B_26_ce0;
output   local_B_26_we0;
output  [31:0] local_B_26_d0;
output  [5:0] local_B_27_address0;
output   local_B_27_ce0;
output   local_B_27_we0;
output  [31:0] local_B_27_d0;
output  [5:0] local_B_28_address0;
output   local_B_28_ce0;
output   local_B_28_we0;
output  [31:0] local_B_28_d0;
output  [5:0] local_B_29_address0;
output   local_B_29_ce0;
output   local_B_29_we0;
output  [31:0] local_B_29_d0;
output  [5:0] local_B_30_address0;
output   local_B_30_ce0;
output   local_B_30_we0;
output  [31:0] local_B_30_d0;
output  [5:0] local_B_31_address0;
output   local_B_31_ce0;
output   local_B_31_we0;
output  [31:0] local_B_31_d0;
output  [5:0] local_B_32_address0;
output   local_B_32_ce0;
output   local_B_32_we0;
output  [31:0] local_B_32_d0;
output  [5:0] local_B_33_address0;
output   local_B_33_ce0;
output   local_B_33_we0;
output  [31:0] local_B_33_d0;
output  [5:0] local_B_34_address0;
output   local_B_34_ce0;
output   local_B_34_we0;
output  [31:0] local_B_34_d0;
output  [5:0] local_B_35_address0;
output   local_B_35_ce0;
output   local_B_35_we0;
output  [31:0] local_B_35_d0;
output  [5:0] local_B_36_address0;
output   local_B_36_ce0;
output   local_B_36_we0;
output  [31:0] local_B_36_d0;
output  [5:0] local_B_37_address0;
output   local_B_37_ce0;
output   local_B_37_we0;
output  [31:0] local_B_37_d0;
output  [5:0] local_B_38_address0;
output   local_B_38_ce0;
output   local_B_38_we0;
output  [31:0] local_B_38_d0;
output  [5:0] local_B_39_address0;
output   local_B_39_ce0;
output   local_B_39_we0;
output  [31:0] local_B_39_d0;
output  [5:0] local_B_40_address0;
output   local_B_40_ce0;
output   local_B_40_we0;
output  [31:0] local_B_40_d0;
output  [5:0] local_B_41_address0;
output   local_B_41_ce0;
output   local_B_41_we0;
output  [31:0] local_B_41_d0;
output  [5:0] local_B_42_address0;
output   local_B_42_ce0;
output   local_B_42_we0;
output  [31:0] local_B_42_d0;
output  [5:0] local_B_43_address0;
output   local_B_43_ce0;
output   local_B_43_we0;
output  [31:0] local_B_43_d0;
output  [5:0] local_B_44_address0;
output   local_B_44_ce0;
output   local_B_44_we0;
output  [31:0] local_B_44_d0;
output  [5:0] local_B_45_address0;
output   local_B_45_ce0;
output   local_B_45_we0;
output  [31:0] local_B_45_d0;
output  [5:0] local_B_46_address0;
output   local_B_46_ce0;
output   local_B_46_we0;
output  [31:0] local_B_46_d0;
output  [5:0] local_B_47_address0;
output   local_B_47_ce0;
output   local_B_47_we0;
output  [31:0] local_B_47_d0;
output  [5:0] local_B_48_address0;
output   local_B_48_ce0;
output   local_B_48_we0;
output  [31:0] local_B_48_d0;
output  [5:0] local_B_49_address0;
output   local_B_49_ce0;
output   local_B_49_we0;
output  [31:0] local_B_49_d0;
output  [5:0] local_B_50_address0;
output   local_B_50_ce0;
output   local_B_50_we0;
output  [31:0] local_B_50_d0;
output  [5:0] local_B_51_address0;
output   local_B_51_ce0;
output   local_B_51_we0;
output  [31:0] local_B_51_d0;
output  [5:0] local_B_52_address0;
output   local_B_52_ce0;
output   local_B_52_we0;
output  [31:0] local_B_52_d0;
output  [5:0] local_B_53_address0;
output   local_B_53_ce0;
output   local_B_53_we0;
output  [31:0] local_B_53_d0;
output  [5:0] local_B_54_address0;
output   local_B_54_ce0;
output   local_B_54_we0;
output  [31:0] local_B_54_d0;
output  [5:0] local_B_55_address0;
output   local_B_55_ce0;
output   local_B_55_we0;
output  [31:0] local_B_55_d0;
output  [5:0] local_B_56_address0;
output   local_B_56_ce0;
output   local_B_56_we0;
output  [31:0] local_B_56_d0;
output  [5:0] local_B_57_address0;
output   local_B_57_ce0;
output   local_B_57_we0;
output  [31:0] local_B_57_d0;
output  [5:0] local_B_58_address0;
output   local_B_58_ce0;
output   local_B_58_we0;
output  [31:0] local_B_58_d0;
output  [5:0] local_B_59_address0;
output   local_B_59_ce0;
output   local_B_59_we0;
output  [31:0] local_B_59_d0;
output  [5:0] local_B_60_address0;
output   local_B_60_ce0;
output   local_B_60_we0;
output  [31:0] local_B_60_d0;
output  [5:0] local_B_61_address0;
output   local_B_61_ce0;
output   local_B_61_we0;
output  [31:0] local_B_61_d0;
output  [5:0] local_B_62_address0;
output   local_B_62_ce0;
output   local_B_62_we0;
output  [31:0] local_B_62_d0;
output  [5:0] local_B_63_address0;
output   local_B_63_ce0;
output   local_B_63_we0;
output  [31:0] local_B_63_d0;
input  [31:0] zext_ln34_1;
input  [61:0] trunc_ln35_1;
input  [61:0] shl_ln;
input  [63:0] B;
output  [6:0] grp_fu_5051_p_din0;
output  [31:0] grp_fu_5051_p_din1;
input  [38:0] grp_fu_5051_p_dout0;
output   grp_fu_5051_p_ce;

reg ap_idle;
reg m_axi_gmem1_ARVALID;
reg m_axi_gmem1_RREADY;
reg local_B_ce0;
reg local_B_we0;
reg local_B_1_ce0;
reg local_B_1_we0;
reg local_B_2_ce0;
reg local_B_2_we0;
reg local_B_3_ce0;
reg local_B_3_we0;
reg local_B_4_ce0;
reg local_B_4_we0;
reg local_B_5_ce0;
reg local_B_5_we0;
reg local_B_6_ce0;
reg local_B_6_we0;
reg local_B_7_ce0;
reg local_B_7_we0;
reg local_B_8_ce0;
reg local_B_8_we0;
reg local_B_9_ce0;
reg local_B_9_we0;
reg local_B_10_ce0;
reg local_B_10_we0;
reg local_B_11_ce0;
reg local_B_11_we0;
reg local_B_12_ce0;
reg local_B_12_we0;
reg local_B_13_ce0;
reg local_B_13_we0;
reg local_B_14_ce0;
reg local_B_14_we0;
reg local_B_15_ce0;
reg local_B_15_we0;
reg local_B_16_ce0;
reg local_B_16_we0;
reg local_B_17_ce0;
reg local_B_17_we0;
reg local_B_18_ce0;
reg local_B_18_we0;
reg local_B_19_ce0;
reg local_B_19_we0;
reg local_B_20_ce0;
reg local_B_20_we0;
reg local_B_21_ce0;
reg local_B_21_we0;
reg local_B_22_ce0;
reg local_B_22_we0;
reg local_B_23_ce0;
reg local_B_23_we0;
reg local_B_24_ce0;
reg local_B_24_we0;
reg local_B_25_ce0;
reg local_B_25_we0;
reg local_B_26_ce0;
reg local_B_26_we0;
reg local_B_27_ce0;
reg local_B_27_we0;
reg local_B_28_ce0;
reg local_B_28_we0;
reg local_B_29_ce0;
reg local_B_29_we0;
reg local_B_30_ce0;
reg local_B_30_we0;
reg local_B_31_ce0;
reg local_B_31_we0;
reg local_B_32_ce0;
reg local_B_32_we0;
reg local_B_33_ce0;
reg local_B_33_we0;
reg local_B_34_ce0;
reg local_B_34_we0;
reg local_B_35_ce0;
reg local_B_35_we0;
reg local_B_36_ce0;
reg local_B_36_we0;
reg local_B_37_ce0;
reg local_B_37_we0;
reg local_B_38_ce0;
reg local_B_38_we0;
reg local_B_39_ce0;
reg local_B_39_we0;
reg local_B_40_ce0;
reg local_B_40_we0;
reg local_B_41_ce0;
reg local_B_41_we0;
reg local_B_42_ce0;
reg local_B_42_we0;
reg local_B_43_ce0;
reg local_B_43_we0;
reg local_B_44_ce0;
reg local_B_44_we0;
reg local_B_45_ce0;
reg local_B_45_we0;
reg local_B_46_ce0;
reg local_B_46_we0;
reg local_B_47_ce0;
reg local_B_47_we0;
reg local_B_48_ce0;
reg local_B_48_we0;
reg local_B_49_ce0;
reg local_B_49_we0;
reg local_B_50_ce0;
reg local_B_50_we0;
reg local_B_51_ce0;
reg local_B_51_we0;
reg local_B_52_ce0;
reg local_B_52_we0;
reg local_B_53_ce0;
reg local_B_53_we0;
reg local_B_54_ce0;
reg local_B_54_we0;
reg local_B_55_ce0;
reg local_B_55_we0;
reg local_B_56_ce0;
reg local_B_56_we0;
reg local_B_57_ce0;
reg local_B_57_we0;
reg local_B_58_ce0;
reg local_B_58_we0;
reg local_B_59_ce0;
reg local_B_59_we0;
reg local_B_60_ce0;
reg local_B_60_we0;
reg local_B_61_ce0;
reg local_B_61_we0;
reg local_B_62_ce0;
reg local_B_62_we0;
reg local_B_63_ce0;
reg local_B_63_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
reg   [0:0] or_ln53_reg_1502;
reg   [0:0] or_ln53_reg_1502_pp0_iter3_reg;
reg    ap_block_state5_io;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
reg    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln53_fu_1249_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem1_blk_n_AR;
reg    ap_block_pp0_stage0_11001;
wire   [38:0] zext_ln34_1_cast_fu_1227_p1;
reg   [38:0] zext_ln34_1_cast_reg_1493;
reg   [0:0] icmp_ln53_reg_1498;
wire   [0:0] or_ln53_fu_1273_p2;
reg   [0:0] or_ln53_reg_1502_pp0_iter1_reg;
reg   [0:0] or_ln53_reg_1502_pp0_iter2_reg;
wire   [6:0] select_ln53_fu_1279_p3;
reg   [6:0] select_ln53_reg_1506;
reg   [6:0] select_ln53_reg_1506_pp0_iter1_reg;
reg   [6:0] select_ln53_reg_1506_pp0_iter2_reg;
reg   [6:0] select_ln53_reg_1506_pp0_iter3_reg;
reg   [6:0] select_ln53_reg_1506_pp0_iter4_reg;
reg   [6:0] select_ln53_reg_1506_pp0_iter5_reg;
reg   [6:0] select_ln53_reg_1506_pp0_iter6_reg;
reg   [6:0] select_ln53_reg_1506_pp0_iter7_reg;
reg   [6:0] select_ln53_reg_1506_pp0_iter8_reg;
reg   [6:0] select_ln53_reg_1506_pp0_iter9_reg;
reg   [6:0] select_ln53_reg_1506_pp0_iter10_reg;
reg   [6:0] select_ln53_reg_1506_pp0_iter11_reg;
wire   [6:0] select_ln53_1_fu_1293_p3;
reg   [6:0] select_ln53_1_reg_1511;
wire   [5:0] trunc_ln53_fu_1301_p1;
reg   [5:0] trunc_ln53_reg_1516;
reg   [5:0] trunc_ln53_reg_1516_pp0_iter1_reg;
reg   [5:0] trunc_ln53_reg_1516_pp0_iter2_reg;
reg   [5:0] trunc_ln53_reg_1516_pp0_iter3_reg;
reg   [5:0] trunc_ln53_reg_1516_pp0_iter4_reg;
reg   [5:0] trunc_ln53_reg_1516_pp0_iter5_reg;
reg   [5:0] trunc_ln53_reg_1516_pp0_iter6_reg;
reg   [5:0] trunc_ln53_reg_1516_pp0_iter7_reg;
reg   [5:0] trunc_ln53_reg_1516_pp0_iter8_reg;
reg   [5:0] trunc_ln53_reg_1516_pp0_iter9_reg;
reg   [5:0] trunc_ln53_reg_1516_pp0_iter10_reg;
reg   [5:0] trunc_ln53_reg_1516_pp0_iter11_reg;
wire   [38:0] zext_ln53_fu_1326_p1;
reg   [38:0] mul_ln53_reg_1525;
reg   [61:0] sext_ln54_mid2_v_reg_1530;
wire   [31:0] bitcast_ln56_fu_1386_p1;
reg   [31:0] bitcast_ln56_reg_1545;
reg   [0:0] ap_phi_mux_first_iter_1_phi_fu_1219_p4;
wire    ap_loop_init;
wire   [63:0] zext_ln54_fu_1390_p1;
wire  signed [63:0] sext_ln53_fu_1370_p1;
reg   [6:0] jj_fu_336;
wire   [6:0] add_ln54_fu_1305_p2;
reg   [6:0] ap_sig_allocacmp_jj_load;
reg   [6:0] kk_fu_340;
reg   [6:0] ap_sig_allocacmp_kk_load;
reg   [12:0] indvar_flatten163_fu_344;
wire   [12:0] add_ln53_fu_1255_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten163_load;
wire   [0:0] icmp_ln54_fu_1267_p2;
wire   [6:0] add_ln53_4_fu_1287_p2;
wire   [61:0] zext_ln53_1_fu_1334_p1;
wire   [61:0] add_ln53_1_fu_1337_p2;
wire   [61:0] add_ln53_2_fu_1342_p2;
wire   [63:0] sext_ln54_mid2_v_v_v_v_fu_1347_p3;
wire   [63:0] add_ln53_3_fu_1355_p2;
reg    grp_fu_1329_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_1161;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrix_mul_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln53_fu_1249_p2 == 1'd0))) begin
            indvar_flatten163_fu_344 <= add_ln53_fu_1255_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten163_fu_344 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln53_fu_1249_p2 == 1'd0))) begin
            jj_fu_336 <= add_ln54_fu_1305_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            jj_fu_336 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln53_fu_1249_p2 == 1'd0))) begin
            kk_fu_340 <= select_ln53_1_fu_1293_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            kk_fu_340 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        bitcast_ln56_reg_1545 <= bitcast_ln56_fu_1386_p1;
        mul_ln53_reg_1525 <= grp_fu_5051_p_dout0;
        or_ln53_reg_1502_pp0_iter2_reg <= or_ln53_reg_1502_pp0_iter1_reg;
        or_ln53_reg_1502_pp0_iter3_reg <= or_ln53_reg_1502_pp0_iter2_reg;
        select_ln53_reg_1506_pp0_iter10_reg <= select_ln53_reg_1506_pp0_iter9_reg;
        select_ln53_reg_1506_pp0_iter11_reg <= select_ln53_reg_1506_pp0_iter10_reg;
        select_ln53_reg_1506_pp0_iter2_reg <= select_ln53_reg_1506_pp0_iter1_reg;
        select_ln53_reg_1506_pp0_iter3_reg <= select_ln53_reg_1506_pp0_iter2_reg;
        select_ln53_reg_1506_pp0_iter4_reg <= select_ln53_reg_1506_pp0_iter3_reg;
        select_ln53_reg_1506_pp0_iter5_reg <= select_ln53_reg_1506_pp0_iter4_reg;
        select_ln53_reg_1506_pp0_iter6_reg <= select_ln53_reg_1506_pp0_iter5_reg;
        select_ln53_reg_1506_pp0_iter7_reg <= select_ln53_reg_1506_pp0_iter6_reg;
        select_ln53_reg_1506_pp0_iter8_reg <= select_ln53_reg_1506_pp0_iter7_reg;
        select_ln53_reg_1506_pp0_iter9_reg <= select_ln53_reg_1506_pp0_iter8_reg;
        sext_ln54_mid2_v_reg_1530 <= {{add_ln53_3_fu_1355_p2[63:2]}};
        trunc_ln53_reg_1516_pp0_iter10_reg <= trunc_ln53_reg_1516_pp0_iter9_reg;
        trunc_ln53_reg_1516_pp0_iter11_reg <= trunc_ln53_reg_1516_pp0_iter10_reg;
        trunc_ln53_reg_1516_pp0_iter2_reg <= trunc_ln53_reg_1516_pp0_iter1_reg;
        trunc_ln53_reg_1516_pp0_iter3_reg <= trunc_ln53_reg_1516_pp0_iter2_reg;
        trunc_ln53_reg_1516_pp0_iter4_reg <= trunc_ln53_reg_1516_pp0_iter3_reg;
        trunc_ln53_reg_1516_pp0_iter5_reg <= trunc_ln53_reg_1516_pp0_iter4_reg;
        trunc_ln53_reg_1516_pp0_iter6_reg <= trunc_ln53_reg_1516_pp0_iter5_reg;
        trunc_ln53_reg_1516_pp0_iter7_reg <= trunc_ln53_reg_1516_pp0_iter6_reg;
        trunc_ln53_reg_1516_pp0_iter8_reg <= trunc_ln53_reg_1516_pp0_iter7_reg;
        trunc_ln53_reg_1516_pp0_iter9_reg <= trunc_ln53_reg_1516_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln53_reg_1498 <= icmp_ln53_fu_1249_p2;
        or_ln53_reg_1502_pp0_iter1_reg <= or_ln53_reg_1502;
        select_ln53_reg_1506_pp0_iter1_reg <= select_ln53_reg_1506;
        trunc_ln53_reg_1516_pp0_iter1_reg <= trunc_ln53_reg_1516;
        zext_ln34_1_cast_reg_1493[31 : 0] <= zext_ln34_1_cast_fu_1227_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln53_fu_1249_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_ln53_reg_1502 <= or_ln53_fu_1273_p2;
        select_ln53_1_reg_1511 <= select_ln53_1_fu_1293_p3;
        select_ln53_reg_1506 <= select_ln53_fu_1279_p3;
        trunc_ln53_reg_1516 <= trunc_ln53_fu_1301_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln53_fu_1249_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_1161)) begin
            ap_phi_mux_first_iter_1_phi_fu_1219_p4 = 1'd0;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_first_iter_1_phi_fu_1219_p4 = 1'd1;
        end else begin
            ap_phi_mux_first_iter_1_phi_fu_1219_p4 = 1'd0;
        end
    end else begin
        ap_phi_mux_first_iter_1_phi_fu_1219_p4 = 1'd0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten163_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten163_load = indvar_flatten163_fu_344;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_jj_load = 7'd0;
    end else begin
        ap_sig_allocacmp_jj_load = jj_fu_336;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_kk_load = 7'd0;
    end else begin
        ap_sig_allocacmp_kk_load = kk_fu_340;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (or_ln53_reg_1502_pp0_iter3_reg == 1'd1))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1329_ce = 1'b1;
    end else begin
        grp_fu_1329_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_10_ce0 = 1'b1;
    end else begin
        local_B_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd10) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_10_we0 = 1'b1;
    end else begin
        local_B_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_11_ce0 = 1'b1;
    end else begin
        local_B_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd11) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_11_we0 = 1'b1;
    end else begin
        local_B_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_12_ce0 = 1'b1;
    end else begin
        local_B_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd12) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_12_we0 = 1'b1;
    end else begin
        local_B_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_13_ce0 = 1'b1;
    end else begin
        local_B_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd13) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_13_we0 = 1'b1;
    end else begin
        local_B_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_14_ce0 = 1'b1;
    end else begin
        local_B_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd14) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_14_we0 = 1'b1;
    end else begin
        local_B_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_15_ce0 = 1'b1;
    end else begin
        local_B_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd15) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_15_we0 = 1'b1;
    end else begin
        local_B_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_16_ce0 = 1'b1;
    end else begin
        local_B_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd16) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_16_we0 = 1'b1;
    end else begin
        local_B_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_17_ce0 = 1'b1;
    end else begin
        local_B_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd17) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_17_we0 = 1'b1;
    end else begin
        local_B_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_18_ce0 = 1'b1;
    end else begin
        local_B_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd18) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_18_we0 = 1'b1;
    end else begin
        local_B_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_19_ce0 = 1'b1;
    end else begin
        local_B_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd19) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_19_we0 = 1'b1;
    end else begin
        local_B_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_1_ce0 = 1'b1;
    end else begin
        local_B_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd1) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_1_we0 = 1'b1;
    end else begin
        local_B_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_20_ce0 = 1'b1;
    end else begin
        local_B_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd20) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_20_we0 = 1'b1;
    end else begin
        local_B_20_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_21_ce0 = 1'b1;
    end else begin
        local_B_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd21) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_21_we0 = 1'b1;
    end else begin
        local_B_21_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_22_ce0 = 1'b1;
    end else begin
        local_B_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd22) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_22_we0 = 1'b1;
    end else begin
        local_B_22_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_23_ce0 = 1'b1;
    end else begin
        local_B_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd23) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_23_we0 = 1'b1;
    end else begin
        local_B_23_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_24_ce0 = 1'b1;
    end else begin
        local_B_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd24) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_24_we0 = 1'b1;
    end else begin
        local_B_24_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_25_ce0 = 1'b1;
    end else begin
        local_B_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd25) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_25_we0 = 1'b1;
    end else begin
        local_B_25_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_26_ce0 = 1'b1;
    end else begin
        local_B_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd26) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_26_we0 = 1'b1;
    end else begin
        local_B_26_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_27_ce0 = 1'b1;
    end else begin
        local_B_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd27) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_27_we0 = 1'b1;
    end else begin
        local_B_27_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_28_ce0 = 1'b1;
    end else begin
        local_B_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd28) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_28_we0 = 1'b1;
    end else begin
        local_B_28_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_29_ce0 = 1'b1;
    end else begin
        local_B_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd29) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_29_we0 = 1'b1;
    end else begin
        local_B_29_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_2_ce0 = 1'b1;
    end else begin
        local_B_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd2) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_2_we0 = 1'b1;
    end else begin
        local_B_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_30_ce0 = 1'b1;
    end else begin
        local_B_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd30) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_30_we0 = 1'b1;
    end else begin
        local_B_30_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_31_ce0 = 1'b1;
    end else begin
        local_B_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd31) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_31_we0 = 1'b1;
    end else begin
        local_B_31_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_32_ce0 = 1'b1;
    end else begin
        local_B_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd32) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_32_we0 = 1'b1;
    end else begin
        local_B_32_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_33_ce0 = 1'b1;
    end else begin
        local_B_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd33) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_33_we0 = 1'b1;
    end else begin
        local_B_33_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_34_ce0 = 1'b1;
    end else begin
        local_B_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd34) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_34_we0 = 1'b1;
    end else begin
        local_B_34_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_35_ce0 = 1'b1;
    end else begin
        local_B_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd35) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_35_we0 = 1'b1;
    end else begin
        local_B_35_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_36_ce0 = 1'b1;
    end else begin
        local_B_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd36) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_36_we0 = 1'b1;
    end else begin
        local_B_36_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_37_ce0 = 1'b1;
    end else begin
        local_B_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd37) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_37_we0 = 1'b1;
    end else begin
        local_B_37_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_38_ce0 = 1'b1;
    end else begin
        local_B_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd38) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_38_we0 = 1'b1;
    end else begin
        local_B_38_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_39_ce0 = 1'b1;
    end else begin
        local_B_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd39) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_39_we0 = 1'b1;
    end else begin
        local_B_39_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_3_ce0 = 1'b1;
    end else begin
        local_B_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd3) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_3_we0 = 1'b1;
    end else begin
        local_B_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_40_ce0 = 1'b1;
    end else begin
        local_B_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd40) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_40_we0 = 1'b1;
    end else begin
        local_B_40_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_41_ce0 = 1'b1;
    end else begin
        local_B_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd41) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_41_we0 = 1'b1;
    end else begin
        local_B_41_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_42_ce0 = 1'b1;
    end else begin
        local_B_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd42) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_42_we0 = 1'b1;
    end else begin
        local_B_42_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_43_ce0 = 1'b1;
    end else begin
        local_B_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd43) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_43_we0 = 1'b1;
    end else begin
        local_B_43_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_44_ce0 = 1'b1;
    end else begin
        local_B_44_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd44) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_44_we0 = 1'b1;
    end else begin
        local_B_44_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_45_ce0 = 1'b1;
    end else begin
        local_B_45_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd45) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_45_we0 = 1'b1;
    end else begin
        local_B_45_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_46_ce0 = 1'b1;
    end else begin
        local_B_46_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd46) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_46_we0 = 1'b1;
    end else begin
        local_B_46_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_47_ce0 = 1'b1;
    end else begin
        local_B_47_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd47) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_47_we0 = 1'b1;
    end else begin
        local_B_47_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_48_ce0 = 1'b1;
    end else begin
        local_B_48_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd48) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_48_we0 = 1'b1;
    end else begin
        local_B_48_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_49_ce0 = 1'b1;
    end else begin
        local_B_49_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd49) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_49_we0 = 1'b1;
    end else begin
        local_B_49_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_4_ce0 = 1'b1;
    end else begin
        local_B_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd4) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_4_we0 = 1'b1;
    end else begin
        local_B_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_50_ce0 = 1'b1;
    end else begin
        local_B_50_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd50) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_50_we0 = 1'b1;
    end else begin
        local_B_50_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_51_ce0 = 1'b1;
    end else begin
        local_B_51_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd51) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_51_we0 = 1'b1;
    end else begin
        local_B_51_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_52_ce0 = 1'b1;
    end else begin
        local_B_52_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd52) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_52_we0 = 1'b1;
    end else begin
        local_B_52_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_53_ce0 = 1'b1;
    end else begin
        local_B_53_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd53) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_53_we0 = 1'b1;
    end else begin
        local_B_53_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_54_ce0 = 1'b1;
    end else begin
        local_B_54_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd54) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_54_we0 = 1'b1;
    end else begin
        local_B_54_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_55_ce0 = 1'b1;
    end else begin
        local_B_55_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd55) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_55_we0 = 1'b1;
    end else begin
        local_B_55_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_56_ce0 = 1'b1;
    end else begin
        local_B_56_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd56) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_56_we0 = 1'b1;
    end else begin
        local_B_56_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_57_ce0 = 1'b1;
    end else begin
        local_B_57_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd57) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_57_we0 = 1'b1;
    end else begin
        local_B_57_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_58_ce0 = 1'b1;
    end else begin
        local_B_58_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd58) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_58_we0 = 1'b1;
    end else begin
        local_B_58_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_59_ce0 = 1'b1;
    end else begin
        local_B_59_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd59) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_59_we0 = 1'b1;
    end else begin
        local_B_59_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_5_ce0 = 1'b1;
    end else begin
        local_B_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd5) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_5_we0 = 1'b1;
    end else begin
        local_B_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_60_ce0 = 1'b1;
    end else begin
        local_B_60_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd60) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_60_we0 = 1'b1;
    end else begin
        local_B_60_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_61_ce0 = 1'b1;
    end else begin
        local_B_61_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd61) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_61_we0 = 1'b1;
    end else begin
        local_B_61_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_62_ce0 = 1'b1;
    end else begin
        local_B_62_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd62) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_62_we0 = 1'b1;
    end else begin
        local_B_62_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_63_ce0 = 1'b1;
    end else begin
        local_B_63_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd63) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_63_we0 = 1'b1;
    end else begin
        local_B_63_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_6_ce0 = 1'b1;
    end else begin
        local_B_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd6) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_6_we0 = 1'b1;
    end else begin
        local_B_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_7_ce0 = 1'b1;
    end else begin
        local_B_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd7) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_7_we0 = 1'b1;
    end else begin
        local_B_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_8_ce0 = 1'b1;
    end else begin
        local_B_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd8) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_8_we0 = 1'b1;
    end else begin
        local_B_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_9_ce0 = 1'b1;
    end else begin
        local_B_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd9) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_9_we0 = 1'b1;
    end else begin
        local_B_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_ce0 = 1'b1;
    end else begin
        local_B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln53_reg_1516_pp0_iter11_reg == 6'd0) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_B_we0 = 1'b1;
    end else begin
        local_B_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln53_reg_1502_pp0_iter3_reg == 1'd1))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln53_1_fu_1337_p2 = (trunc_ln35_1 + zext_ln53_1_fu_1334_p1);

assign add_ln53_2_fu_1342_p2 = (add_ln53_1_fu_1337_p2 + shl_ln);

assign add_ln53_3_fu_1355_p2 = (sext_ln54_mid2_v_v_v_v_fu_1347_p3 + B);

assign add_ln53_4_fu_1287_p2 = (ap_sig_allocacmp_kk_load + 7'd1);

assign add_ln53_fu_1255_p2 = (ap_sig_allocacmp_indvar_flatten163_load + 13'd1);

assign add_ln54_fu_1305_p2 = (select_ln53_fu_1279_p3 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11 = (m_axi_gmem1_RVALID == 1'b0);
end

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((m_axi_gmem1_ARREADY == 1'b0) & (or_ln53_reg_1502_pp0_iter3_reg == 1'd1));
end

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1161 = ((icmp_ln53_reg_1498 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln56_fu_1386_p1 = m_axi_gmem1_RDATA;

assign grp_fu_5051_p_ce = grp_fu_1329_ce;

assign grp_fu_5051_p_din0 = zext_ln53_fu_1326_p1;

assign grp_fu_5051_p_din1 = zext_ln34_1_cast_reg_1493;

assign icmp_ln53_fu_1249_p2 = ((ap_sig_allocacmp_indvar_flatten163_load == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_1267_p2 = ((ap_sig_allocacmp_jj_load == 7'd64) ? 1'b1 : 1'b0);

assign local_B_10_address0 = zext_ln54_fu_1390_p1;

assign local_B_10_d0 = bitcast_ln56_reg_1545;

assign local_B_11_address0 = zext_ln54_fu_1390_p1;

assign local_B_11_d0 = bitcast_ln56_reg_1545;

assign local_B_12_address0 = zext_ln54_fu_1390_p1;

assign local_B_12_d0 = bitcast_ln56_reg_1545;

assign local_B_13_address0 = zext_ln54_fu_1390_p1;

assign local_B_13_d0 = bitcast_ln56_reg_1545;

assign local_B_14_address0 = zext_ln54_fu_1390_p1;

assign local_B_14_d0 = bitcast_ln56_reg_1545;

assign local_B_15_address0 = zext_ln54_fu_1390_p1;

assign local_B_15_d0 = bitcast_ln56_reg_1545;

assign local_B_16_address0 = zext_ln54_fu_1390_p1;

assign local_B_16_d0 = bitcast_ln56_reg_1545;

assign local_B_17_address0 = zext_ln54_fu_1390_p1;

assign local_B_17_d0 = bitcast_ln56_reg_1545;

assign local_B_18_address0 = zext_ln54_fu_1390_p1;

assign local_B_18_d0 = bitcast_ln56_reg_1545;

assign local_B_19_address0 = zext_ln54_fu_1390_p1;

assign local_B_19_d0 = bitcast_ln56_reg_1545;

assign local_B_1_address0 = zext_ln54_fu_1390_p1;

assign local_B_1_d0 = bitcast_ln56_reg_1545;

assign local_B_20_address0 = zext_ln54_fu_1390_p1;

assign local_B_20_d0 = bitcast_ln56_reg_1545;

assign local_B_21_address0 = zext_ln54_fu_1390_p1;

assign local_B_21_d0 = bitcast_ln56_reg_1545;

assign local_B_22_address0 = zext_ln54_fu_1390_p1;

assign local_B_22_d0 = bitcast_ln56_reg_1545;

assign local_B_23_address0 = zext_ln54_fu_1390_p1;

assign local_B_23_d0 = bitcast_ln56_reg_1545;

assign local_B_24_address0 = zext_ln54_fu_1390_p1;

assign local_B_24_d0 = bitcast_ln56_reg_1545;

assign local_B_25_address0 = zext_ln54_fu_1390_p1;

assign local_B_25_d0 = bitcast_ln56_reg_1545;

assign local_B_26_address0 = zext_ln54_fu_1390_p1;

assign local_B_26_d0 = bitcast_ln56_reg_1545;

assign local_B_27_address0 = zext_ln54_fu_1390_p1;

assign local_B_27_d0 = bitcast_ln56_reg_1545;

assign local_B_28_address0 = zext_ln54_fu_1390_p1;

assign local_B_28_d0 = bitcast_ln56_reg_1545;

assign local_B_29_address0 = zext_ln54_fu_1390_p1;

assign local_B_29_d0 = bitcast_ln56_reg_1545;

assign local_B_2_address0 = zext_ln54_fu_1390_p1;

assign local_B_2_d0 = bitcast_ln56_reg_1545;

assign local_B_30_address0 = zext_ln54_fu_1390_p1;

assign local_B_30_d0 = bitcast_ln56_reg_1545;

assign local_B_31_address0 = zext_ln54_fu_1390_p1;

assign local_B_31_d0 = bitcast_ln56_reg_1545;

assign local_B_32_address0 = zext_ln54_fu_1390_p1;

assign local_B_32_d0 = bitcast_ln56_reg_1545;

assign local_B_33_address0 = zext_ln54_fu_1390_p1;

assign local_B_33_d0 = bitcast_ln56_reg_1545;

assign local_B_34_address0 = zext_ln54_fu_1390_p1;

assign local_B_34_d0 = bitcast_ln56_reg_1545;

assign local_B_35_address0 = zext_ln54_fu_1390_p1;

assign local_B_35_d0 = bitcast_ln56_reg_1545;

assign local_B_36_address0 = zext_ln54_fu_1390_p1;

assign local_B_36_d0 = bitcast_ln56_reg_1545;

assign local_B_37_address0 = zext_ln54_fu_1390_p1;

assign local_B_37_d0 = bitcast_ln56_reg_1545;

assign local_B_38_address0 = zext_ln54_fu_1390_p1;

assign local_B_38_d0 = bitcast_ln56_reg_1545;

assign local_B_39_address0 = zext_ln54_fu_1390_p1;

assign local_B_39_d0 = bitcast_ln56_reg_1545;

assign local_B_3_address0 = zext_ln54_fu_1390_p1;

assign local_B_3_d0 = bitcast_ln56_reg_1545;

assign local_B_40_address0 = zext_ln54_fu_1390_p1;

assign local_B_40_d0 = bitcast_ln56_reg_1545;

assign local_B_41_address0 = zext_ln54_fu_1390_p1;

assign local_B_41_d0 = bitcast_ln56_reg_1545;

assign local_B_42_address0 = zext_ln54_fu_1390_p1;

assign local_B_42_d0 = bitcast_ln56_reg_1545;

assign local_B_43_address0 = zext_ln54_fu_1390_p1;

assign local_B_43_d0 = bitcast_ln56_reg_1545;

assign local_B_44_address0 = zext_ln54_fu_1390_p1;

assign local_B_44_d0 = bitcast_ln56_reg_1545;

assign local_B_45_address0 = zext_ln54_fu_1390_p1;

assign local_B_45_d0 = bitcast_ln56_reg_1545;

assign local_B_46_address0 = zext_ln54_fu_1390_p1;

assign local_B_46_d0 = bitcast_ln56_reg_1545;

assign local_B_47_address0 = zext_ln54_fu_1390_p1;

assign local_B_47_d0 = bitcast_ln56_reg_1545;

assign local_B_48_address0 = zext_ln54_fu_1390_p1;

assign local_B_48_d0 = bitcast_ln56_reg_1545;

assign local_B_49_address0 = zext_ln54_fu_1390_p1;

assign local_B_49_d0 = bitcast_ln56_reg_1545;

assign local_B_4_address0 = zext_ln54_fu_1390_p1;

assign local_B_4_d0 = bitcast_ln56_reg_1545;

assign local_B_50_address0 = zext_ln54_fu_1390_p1;

assign local_B_50_d0 = bitcast_ln56_reg_1545;

assign local_B_51_address0 = zext_ln54_fu_1390_p1;

assign local_B_51_d0 = bitcast_ln56_reg_1545;

assign local_B_52_address0 = zext_ln54_fu_1390_p1;

assign local_B_52_d0 = bitcast_ln56_reg_1545;

assign local_B_53_address0 = zext_ln54_fu_1390_p1;

assign local_B_53_d0 = bitcast_ln56_reg_1545;

assign local_B_54_address0 = zext_ln54_fu_1390_p1;

assign local_B_54_d0 = bitcast_ln56_reg_1545;

assign local_B_55_address0 = zext_ln54_fu_1390_p1;

assign local_B_55_d0 = bitcast_ln56_reg_1545;

assign local_B_56_address0 = zext_ln54_fu_1390_p1;

assign local_B_56_d0 = bitcast_ln56_reg_1545;

assign local_B_57_address0 = zext_ln54_fu_1390_p1;

assign local_B_57_d0 = bitcast_ln56_reg_1545;

assign local_B_58_address0 = zext_ln54_fu_1390_p1;

assign local_B_58_d0 = bitcast_ln56_reg_1545;

assign local_B_59_address0 = zext_ln54_fu_1390_p1;

assign local_B_59_d0 = bitcast_ln56_reg_1545;

assign local_B_5_address0 = zext_ln54_fu_1390_p1;

assign local_B_5_d0 = bitcast_ln56_reg_1545;

assign local_B_60_address0 = zext_ln54_fu_1390_p1;

assign local_B_60_d0 = bitcast_ln56_reg_1545;

assign local_B_61_address0 = zext_ln54_fu_1390_p1;

assign local_B_61_d0 = bitcast_ln56_reg_1545;

assign local_B_62_address0 = zext_ln54_fu_1390_p1;

assign local_B_62_d0 = bitcast_ln56_reg_1545;

assign local_B_63_address0 = zext_ln54_fu_1390_p1;

assign local_B_63_d0 = bitcast_ln56_reg_1545;

assign local_B_6_address0 = zext_ln54_fu_1390_p1;

assign local_B_6_d0 = bitcast_ln56_reg_1545;

assign local_B_7_address0 = zext_ln54_fu_1390_p1;

assign local_B_7_d0 = bitcast_ln56_reg_1545;

assign local_B_8_address0 = zext_ln54_fu_1390_p1;

assign local_B_8_d0 = bitcast_ln56_reg_1545;

assign local_B_9_address0 = zext_ln54_fu_1390_p1;

assign local_B_9_d0 = bitcast_ln56_reg_1545;

assign local_B_address0 = zext_ln54_fu_1390_p1;

assign local_B_d0 = bitcast_ln56_reg_1545;

assign m_axi_gmem1_ARADDR = sext_ln53_fu_1370_p1;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd64;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 32'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 4'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign or_ln53_fu_1273_p2 = (icmp_ln54_fu_1267_p2 | ap_phi_mux_first_iter_1_phi_fu_1219_p4);

assign select_ln53_1_fu_1293_p3 = ((icmp_ln54_fu_1267_p2[0:0] == 1'b1) ? add_ln53_4_fu_1287_p2 : ap_sig_allocacmp_kk_load);

assign select_ln53_fu_1279_p3 = ((icmp_ln54_fu_1267_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_jj_load);

assign sext_ln53_fu_1370_p1 = $signed(sext_ln54_mid2_v_reg_1530);

assign sext_ln54_mid2_v_v_v_v_fu_1347_p3 = {{add_ln53_2_fu_1342_p2}, {2'd0}};

assign trunc_ln53_fu_1301_p1 = select_ln53_1_fu_1293_p3[5:0];

assign zext_ln34_1_cast_fu_1227_p1 = zext_ln34_1;

assign zext_ln53_1_fu_1334_p1 = mul_ln53_reg_1525;

assign zext_ln53_fu_1326_p1 = select_ln53_1_reg_1511;

assign zext_ln54_fu_1390_p1 = select_ln53_reg_1506_pp0_iter11_reg;

always @ (posedge ap_clk) begin
    zext_ln34_1_cast_reg_1493[38:32] <= 7'b0000000;
end

endmodule //matrix_mul_matrix_mul_Pipeline_VITIS_LOOP_54_9
